name: Build Project

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
         
      - name: Clean
        run: dotnet clean && dotnet nuget locals all --clear

      - name: Publish
        run: dotnet publish ${{ inputs.project_name }} --configuration Release

      - uses: actions/upload-artifact@v3
        with:
            name: ${{ inputs.project_name }}-windows
            path: artifacts/publish/*
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
         
      - name: Clean
        run: dotnet clean && dotnet nuget locals all --clear

      - name: Publish
        run: dotnet publish ${{ inputs.project_name }}/${{ inputs.project_name }}.csproj --configuration Release

      - name: Permissions & Rename
        run: (for f in artifacts/publish/*.linux-x64;do mv $f $f.bin;done) && chmod u+x artifacts/publish/${{ inputs.project_name }}.linux-x64.bin

      - uses: actions/upload-artifact@v3
        with:
            name: ${{ inputs.project_name }}-linux
            path: artifacts/publish/*

  update-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    permissions:
      contents: write
    steps:
      - id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2

      - uses: softprops/action-gh-release@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          files: |
            **/*.bin
            **/*.exe
