name: Export TS Data

on:
  workflow_dispatch:
    inputs:
      game:
        required: true
        type: choice
        options:
          - ETS2
          - ATS
      mods:
        required: false
        type: string
      map_name:
        required: true
        type: string
      map_id:
        required: true
        type: string
  workflow_call:
    inputs:
      game:
        required: true
        type: string
      mods:
        required: false
        type: string
      map_name:
        required: true
        type: string
      map_id:
        required: true
        type: string

jobs:
  export:
    runs-on: exporter
    steps:
      - name: Download exporter
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow_search: true
          name: TsMap.Exporter-linux
          search_artifacts: true
          workflow_conclusion: ""
      - name: Export
        env:
            mods_path: ${{ inputs.mods }}
        run: |
          chmod +x ./TsMap.Exporter.linux-x64.bin
          python3 -c "import os; mods_path = '--mods ' + ','.join([os.path.join('/games/mods', mod) for mod in os.getenv('mods_path').split(',')]) if os.getenv('mods_path') else ''; os.system(f'./TsMap.Exporter.linux-x64.bin -g /games/${{inputs.game}} {mods_path} --map-name ${{inputs.map_name}} --zip-path ${{inputs.map_id}}_export.zip')"
      - name: Upload export
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.map_id}}_export
            path: ${{ inputs.map_id}}_export.zip