name: Export TS Data

on:
  workflow_dispatch:
    inputs:
      game:
        required: true
        type: choice
        options:
          - ETS2
          - ATS
      mods:
        required: false
        type: string
      export_name:
        required: true
        type: string
  workflow_call:
    inputs:
      game:
        required: true
        type: string
      mods:
        required: false
        type: string
      export_name:
        required: true
        type: string

permissions: write-all

jobs:
  download-game:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: dawidd6/action-download-artifact@v3
        with:
          name: "games"
          path: "./games"
          if_no_artifact_found: ignore

      - uses: CyberAndrii/setup-steamcmd@v1
      - uses: CyberAndrii/steam-totp@v1
        id: steam-totp
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}

      - name: Install Game
        env:
          STEAMCMD_USER: ${{ secrets.STEAM_USER }}
          STEAMCMD_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAMCMD_TOTP: ${{ steps.steam-totp.outputs.code }}
          INPUT_GAME: ${{ inputs.game }}
        run: |
          import os
          user = os.getenv("STEAMCMD_USER")
          password = os.getenv("STEAMCMD_PASSWORD")
          totp = os.getenv("STEAMCMD_TOTP")
          game = os.getenv("INPUT_GAME")
          app_id = 227300 if game == "ETS2" else 270880
          os.system(f"steamcmd +force_install_dir ./games/{game} +login {user} {password} {totp} +app_update {app_id} validate +quit")
        shell: python
      
      - uses: actions/upload-artifact@v4
        with:
          name: "games"
          path: "./games"

        
  export-data:
    needs: download-game
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/build.yml
      with:
        project_name: "TsMap.Exporter"
        only_linux: true
    
    - uses: dawidd6/action-download-artifact@v3
      with:
        name: "games"
        path: "./games"
        search_artifacts: true
        if_no_artifact_found: fail
      
    - name: Export Data
      run: ./bin/TsMap.Exporter.linux-x64.bin ./games/${{ inputs.game }} ${{ inputs.export_name }}.zip
        
    - uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.export_name }}.zip"
        path: "${{ inputs.export_name }}.zip"