name: Builds

on:
  push:
    branches: [ main ]
    tags: ["*"]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        proj_name: [TsMap.Canvas, TsMap.Exporter]
    uses: ./.github/workflows/build.yml
    with:
      project_name: ${{ matrix.proj_name }}
  
  export:
    strategy:
      matrix:
        export_conf: ${{ vars.GAMES_EXPORT }}
    needs: build
    uses: ./.github/workflows/export.yml
    with:
      game: ${{ matrix.export_conf.game}}
      export_name: ${{ matrix.export_conf.export_name}}