name: Build & Publish

on:
  push:
    branches: [ main ]
    tags: ["*"]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        proj_name: [TsMap.Canvas, TsMap.Exporter]
    uses: ./.github/workflows/build.yml
    with:
      project_name: ${{ matrix.proj_name }}
  
  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
  
  